### ISSUE TITLE
Examples about Macaroons and Biscuits are currently inappropriate 

### ISSUE THREAD

**Issue by Denisthemalice** [ietf-wg-gnap/gnap-resource-servers#28] opened 2021-05-29 18:29 UTC
The text states:

> Some token formats, such as Macaroons and Biscuits, allow for the RS to derive sub-tokens without having to call the AS as described in Section 4.

Since there is no reference, nor an informative annex, that describes how this can be done, the sentence should be removed.

**Comment by jricher** [comment] 2021-05-30 14:18
Duplicate of #16

**Closed by jricher** 2021-05-30 14:18 UTC
