### ISSUE TITLE
Insufficient description of two fields from RS-facing AS Discovery (editorial)

### ISSUE THREAD

**Issue by Denisthemalice** [ietf-wg-gnap/gnap-resource-servers#40] opened 2021-07-18 06:48 UTC
In section 3.1, RS-facing AS Discovery, five fields are described:

- introspection_endpoint (string): OPTIONAL.
- token_formats_supported (array of strings): 
- resource_registration_endpoint (string): 
- grant_request_endpoint (string): REQUIRED. 
- key_proofs_supported (array of strings) OPTIONAL.

For two of them, it should be indicated whether they are REQUIRED or OPTIONAL.

**Comment by jricher** [comment] 2023-10-10 01:34
duplicate of #60

**Closed by jricher** 2023-10-10 01:34 UTC
